version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: web
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d