spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: web
      username: user
      password: password
      authentication-database: admin  #Authentication database

frontend: https://9305-87-251-79-166.ngrok-free.app